version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: "benit-app-db"
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
  beint-app-api:
    container_name: "benit-app-api"
    build:
      context: ./backend/beint-app-api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    depends_on:
      - postgres
    env_file:
      - .env
  beint-app:
    container_name: "beint-app"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=${BASE_URL}
    ports:
      - ${APP_PORT}:80
