version: '3'
services:
  beint-app-dev:
    container_name: "beint-app-dev"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:9000/api
    ports:
      - 3001:80
